version: "2.0"
services:
  mongodb:
    image: mongo
    container_name: mongodatabase
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27018:27017
    restart: unless-stopped
    volumes:
      - /root/database:/data/db

  web:
    network_mode: host
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_DEBUG: 1
